# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0003_auto_20170227_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='f',
        ),
        migrations.AlterField(
            model_name='courses',
            name='a',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='courses',
            name='b',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='courses',
            name='c',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='courses',
            name='credit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='courses',
            name='d',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
